[versions]
mapstruct = "1.6.3"
springdoc = "2.6.0"
lombokMapstructBinding = "0.2.0"
springBootDependencies = "4.0.2"

[libraries]
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstructProcessor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
springdocWebmvcUi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
lombokMapstructBinding = { module = "org.projectlombok:lombok-mapstruct-binding", version.ref = "lombokMapstructBinding" }
springBootDependencies = { module  = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBootDependencies"}