[versions]
mapstruct = "1.6.3"
springdoc = "3.0.1"
dataFaker = "2.5.4"
lombokMapstructBinding = "0.2.0"
springBootDependencies = "4.0.2"

[libraries]
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstructProcessor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
dataFaker = { module = "net.datafaker:datafaker", version.ref = "dataFaker" }
springdocWebmvcUi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
lombokMapstructBinding = { module = "org.projectlombok:lombok-mapstruct-binding", version.ref = "lombokMapstructBinding" }
springBootDependencies = { module  = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBootDependencies"}